### ISSUE TITLE
Dex visit metrics feiler

### ISSUE THREAD

**Issue by punnerud** [Tirco/PokeMath#3]
Først takk for en flott nettside!
Alle i 1. klasse på skolen til sønnen min får lov til å bruke PokéMath som belønning, når de er ferdige med oppgavene.
Virkelig bidratt til mye god trening av mattekunnskapene 😄

Ser at Dex visningen bruker lang tid på å laste. Kan se ut som det er metrics innsendingen til https://api.countapi.xyz/hit/pokemath.online/dexVisited?callback=cb som feiler.
<img width="1390" alt="dex_visit" src="https://github.com/Tirco/PokeMath/assets/1153515/7c165128-7db4-4d80-85a3-48e8e94529f9">

Kanskje endre på den, eller endre slik at resten av javascript koden ikke må vente på at denne fullfører?
Jeg kan ev se om jeg kan få til en pull-request som fikser det.

Fortsett det gode arbeidet! 😎

**Comment by Tirco** [comment]
Hei!
Takk for at du følger med! :P Jeg har ikke hatt øynene på prosjektet på en stund selv, men jeg får heldigvis e-poster om det er noe galt!


Jeg brukte countapi som en metode for å få gdpr-vennlig statistikk men nå virker det som om den er lagt ned, så da burde jeg fjerne alle referanser til den. 

Jeg ordner det ASAP, men ellers så er alle pull-requests velkomne! :)

**Comment by Tirco** [comment]
Der er det ordnet! (tror jeg... :P)

Dex-en vil være treg om man har veldig mange pokemon, men nå er det ikke countapi som står og snurrer! :)

**Comment by punnerud** [comment]
Takk for raskt svar og løsning. Nå virket det bra igjen 😁😎
